import { IAssignment,AssignmentState,AssignmentType } from './../../../types/assignment';

export const assignments: IAssignment[] = [
  {
    id: "1",
    title: "Mathematics",
    description: "This is a mathematics assignment",
    startDate: "2021-09-01",
    endDate: "2021-09-01",
    publisher: "Azza",
    state: AssignmentState.FINISHED,
    type: AssignmentType.MANUAL,
    module_name: "Mathematics",
    marks: 18,
  },
  {
    id: "2",
    title: "Physics",
    description: "This is a physics quiz",
    startDate: "2021-09-01",
    endDate: "2021-09-01",
    publisher: "Admin",
    state: AssignmentState.UPCOMING,
    type: AssignmentType.AUTOMATED,
    module_name: "Physics",
  },
  {
    id: "3",
    title: "Chemistry",
    description: "This is a chemistry quiz",
    startDate: "2021-09-01",
    endDate: "2021-09-01",
    publisher: "Admin",
    state: AssignmentState.FINISHED,
    type: AssignmentType.AUTOMATED,
    module_name: "Chemistry",
    marks: 10,
  },
  {
    id: "1",
    title: "Mathematics",
    description: "This is a mathematics quiz",
    startDate: "2021-09-01",
    endDate: "2021-09-01",
    publisher: "Admin",
    state: AssignmentState.ONGOING,
    type: AssignmentType.MANUAL,
    module_name: "Mathematics",
  },
  {
    id: "2",
    title: "Physics",
    description: "This is a physics quiz",
    startDate: "2021-09-01",
    endDate: "2021-09-01",
    publisher: "Admin",
    state: AssignmentState.ONGOING,
    type: AssignmentType.MANUAL,
    module_name: "Physics",
  },
  {
    id: "3",
    title: "Chemistry",
    description: "This is a chemistry quiz",
    startDate: "2021-09-01",
    endDate: "2021-09-01",
    publisher: "Admin",
    state: AssignmentState.UPCOMING,
    type: AssignmentType.AUTOMATED,
    module_name: "Chemistry",
  },
  {
    id: "1",
    title: "Mathematics",
    description: "This is a mathematics quiz",
    startDate: "2021-09-01",
    endDate: "2021-09-01",
    publisher: "Admin",
    state: AssignmentState.FINISHED,
    type: AssignmentType.AUTOMATED,
    module_name: "Mathematics",
    marks: 19,
  },
  {
    id: "2",
    title: "Physics",
    description: "This is a physics quiz",
    startDate: "2021-09-01",
    endDate: "2021-09-01",
    publisher: "Admin",
    state: AssignmentState.ONGOING,
    type: AssignmentType.AUTOMATED,
    module_name: "Physics",
  },
  {
    id: "3",
    title: "Chemistry",
    description: "This is a chemistry quiz",
    startDate: "2021-09-01",
    endDate: "2021-09-01",
    publisher: "Admin",
    state: AssignmentState.FINISHED,
    type: AssignmentType.AUTOMATED,
    module_name: "Chemistry",
    marks: 15,
  },
  {
    id: "1",
    title: "Mathematics",
    description: "This is a mathematics quiz",
    startDate: "2021-09-01",
    endDate: "2021-09-01",
    publisher: "Admin",
    state: AssignmentState.UPCOMING,
    type: AssignmentType.AUTOMATED,
    module_name: "Mathematics",
  },
  {
    id: "2",
    title: "Physics",
    description: "This is a physics quiz",
    startDate: "2021-09-01",
    endDate: "2021-09-01",
    publisher: "Admin",
    state: AssignmentState.ONGOING,
    type: AssignmentType.MANUAL,
    module_name: "Physics",
  },
  {
    id: "3",
    title: "Chemistry",
    description: "This is a chemistry quiz",
    startDate: "2021-09-01",
    endDate: "2021-09-01",
    publisher: "Admin",
    state: AssignmentState.FINISHED,
    type: AssignmentType.MANUAL,
    module_name: "Chemistry",
    marks: 12,
  },
];
