import { ChapterWithSections } from '@/types/courses';

const chaptersWithSections: ChapterWithSections[] = [
	{
		name: 'Chapter 1',
		id: '1',
		module_id: '1',
		chapter_number: 1,
		createdAt: new Date(),
		updatedAt: new Date(),
		sections: [
			{
				name: 'Section 1',
				course_id: '1',
				id: '1',
				videos: [
					{
						name: 'Video 1',
						id: '1',
						url: 'https://example.com/video1.mp4',
						section_id: '1',
						teacher_id: '1',
						createdAt: new Date(),
					},
					{
						name: 'Video 2',
						id: '2',
						url: 'https://example.com/video2.mp4',
						section_id: '1',
						teacher_id: '1',
						createdAt: new Date(),
					},
					{
						name: 'Video 2',
						id: '2',
						url: 'https://example.com/video2.mp4',
						section_id: '1',
						teacher_id: '1',
						createdAt: new Date(),
					},
				],
				lectures: [
					{
						name: 'Lecture 1',
						id: '3',
						content: 'This is lecture content 1',
						section_id: '1',
						teacher_id: '1',
						createdAt: new Date(),
					},
					{
						name: 'Lecture 1',
						id: '3',
						content: 'This is lecture content 1',
						section_id: '1',
						teacher_id: '1',
						createdAt: new Date(),
					},
					{
						name: 'Lecture 1',
						id: '3',
						content: 'This is lecture content 1',
						section_id: '1',
						teacher_id: '1',
						createdAt: new Date(),
					},
				],
				note: {
					name: 'Note 1',
					id: '4',
					content: 'This is note content 1',
					section_id: '1',
					teacher_id: '1',
					createdAt: new Date(),
				},
				files: [
					{
						name: 'File 1',
						id: '5',
						section_id: '1',
						teacher_id: '1',
						createdAt: new Date(),
					},
					{
						name: 'File 1',
						id: '5',
						section_id: '1',
						teacher_id: '1',
						createdAt: new Date(),
					},
					{
						name: 'File 1',
						id: '5',
						section_id: '1',
						teacher_id: '1',
						createdAt: new Date(),
					},
					{
						name: 'File 1',
						id: '5',
						section_id: '1',
						teacher_id: '1',
						createdAt: new Date(),
					},
				],
			},
		],
	},
	{
		name: 'Chapter 1',
		id: '1',
		module_id: '1',
		chapter_number: 1,
		createdAt: new Date(),
		updatedAt: new Date(),
		sections: [
			{
				name: 'Section 1',
				course_id: '1',
				id: '1',
				videos: [
					{
						name: 'Video 1',
						id: '1',
						url: 'https://example.com/video1.mp4',
						section_id: '1',
						teacher_id: '1',
						createdAt: new Date(),
					},
					{
						name: 'Video 2',
						id: '2',
						url: 'https://example.com/video2.mp4',
						section_id: '1',
						teacher_id: '1',
						createdAt: new Date(),
					},
					{
						name: 'Video 2',
						id: '2',
						url: 'https://example.com/video2.mp4',
						section_id: '1',
						teacher_id: '1',
						createdAt: new Date(),
					},
				],
				lectures: [
					{
						name: 'Lecture 1',
						id: '3',
						content: 'This is lecture content 1',
						section_id: '1',
						teacher_id: '1',
						createdAt: new Date(),
					},
					{
						name: 'Lecture 1',
						id: '3',
						content: 'This is lecture content 1',
						section_id: '1',
						teacher_id: '1',
						createdAt: new Date(),
					},
					{
						name: 'Lecture 1',
						id: '3',
						content: 'This is lecture content 1',
						section_id: '1',
						teacher_id: '1',
						createdAt: new Date(),
					},
				],
				note: {
					name: 'Note 1',
					id: '4',
					content: 'This is note content 1',
					section_id: '1',
					teacher_id: '1',
					createdAt: new Date(),
				},
				files: [
					{
						name: 'File 1',
						id: '5',
						section_id: '1',
						teacher_id: '1',
						createdAt: new Date(),
					},
					{
						name: 'File 1',
						id: '5',
						section_id: '1',
						teacher_id: '1',
						createdAt: new Date(),
					},
					{
						name: 'File 1',
						id: '5',
						section_id: '1',
						teacher_id: '1',
						createdAt: new Date(),
					},
					{
						name: 'File 1',
						id: '5',
						section_id: '1',
						teacher_id: '1',
						createdAt: new Date(),
					},
				],
			},
		],
	},
	{
		name: 'Chapter 1',
		id: '1',
		module_id: '1',
		chapter_number: 1,
		createdAt: new Date(),
		updatedAt: new Date(),
		sections: [
			{
				name: 'Section 1',
				course_id: '1',
				id: '1',
				videos: [
					{
						name: 'Video 1',
						id: '1',
						url: 'https://example.com/video1.mp4',
						section_id: '1',
						teacher_id: '1',
						createdAt: new Date(),
					},
					{
						name: 'Video 2',
						id: '2',
						url: 'https://example.com/video2.mp4',
						section_id: '1',
						teacher_id: '1',
						createdAt: new Date(),
					},
					{
						name: 'Video 2',
						id: '2',
						url: 'https://example.com/video2.mp4',
						section_id: '1',
						teacher_id: '1',
						createdAt: new Date(),
					},
				],
				lectures: [
					{
						name: 'Lecture 1',
						id: '3',
						content: 'This is lecture content 1',
						section_id: '1',
						teacher_id: '1',
						createdAt: new Date(),
					},
					{
						name: 'Lecture 1',
						id: '3',
						content: 'This is lecture content 1',
						section_id: '1',
						teacher_id: '1',
						createdAt: new Date(),
					},
					{
						name: 'Lecture 1',
						id: '3',
						content: 'This is lecture content 1',
						section_id: '1',
						teacher_id: '1',
						createdAt: new Date(),
					},
				],
				note: {
					name: 'Note 1',
					id: '4',
					content: 'This is note content 1',
					section_id: '1',
					teacher_id: '1',
					createdAt: new Date(),
				},
				files: [
					{
						name: 'File 1',
						id: '5',
						section_id: '1',
						teacher_id: '1',
						createdAt: new Date(),
					},
					{
						name: 'File 1',
						id: '5',
						section_id: '1',
						teacher_id: '1',
						createdAt: new Date(),
					},
					{
						name: 'File 1',
						id: '5',
						section_id: '1',
						teacher_id: '1',
						createdAt: new Date(),
					},
					{
						name: 'File 1',
						id: '5',
						section_id: '1',
						teacher_id: '1',
						createdAt: new Date(),
					},
				],
			},
		],
	},
];

export default chaptersWithSections;
