import {
  ChapterWithSections,
  ModulesWithChapters,
} from "@/types/chapter/courses";

const chaptersWithSections: ChapterWithSections[] = [
  {
    teacher_id: 1,
    description: "This is the description of the chapter",
    name: "Chapter 1",
    id: "1",
    module_id: "1",
    chapter_number: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
    sections: [
      {
        name: "Section 1",
        course_id: "1",
        id: "1",
        videos: [
          {
            name: "Video 1",
            id: "1",
            url: "https://example.com/video1.mp4",
            section_id: "1",
            teacher_id: 1,
            createdAt: new Date(),
            groups: [1, 2, 3],
          },
          {
            name: "Video 2",
            id: "2",
            url: "https://example.com/video2.mp4",
            section_id: "1",
            teacher_id: 1,
            createdAt: new Date(),
            groups: [1, 2, 3],
          },
          {
            name: "Video 2",
            id: "2",
            url: "https://example.com/video2.mp4",
            section_id: "1",
            teacher_id: 1,
            createdAt: new Date(),
            groups: [1, 2, 3],
          },
        ],
        lectures: [
          {
            name: "Lecture 1",
            id: "3",
            content: "This is lecture content 1",
            section_id: "1",
            teacher_id: 1,
            createdAt: new Date(),
            groups: [1, 2, 3],
          },
          {
            name: "Lecture 1",
            id: "3",
            content: "This is lecture content 1",
            section_id: "1",
            teacher_id: 1,
            createdAt: new Date(),
            groups: [1, 2, 3],
          },
          {
            name: "Lecture 1",
            id: "3",
            content: "This is lecture content 1",
            section_id: "1",
            teacher_id: 1,
            createdAt: new Date(),
            groups: [1, 2, 3],
          },
        ],
        note: {
          name: "Note 1",
          id: "4",
          content: "This is note content 1",
          section_id: "1",
          teacher_id: 1,
          createdAt: new Date(),
          groups: [1, 2, 3],
        },
        files: [
          {
            name: "File 1",
            id: "5",
            section_id: "1",
            teacher_id: 1,
            createdAt: new Date(),
            groups: [1, 2, 3],
          },
          {
            name: "File 1",
            id: "5",
            section_id: "1",
            teacher_id: 1,
            createdAt: new Date(),
            groups: [1, 2, 3],
          },
          {
            name: "File 1",
            id: "5",
            section_id: "1",
            teacher_id: 1,
            createdAt: new Date(),
            groups: [1, 2, 3],
          },
          {
            name: "File 1",
            id: "5",
            section_id: "1",
            teacher_id: 1,
            createdAt: new Date(),
            groups: [1, 2, 3],
          },
        ],
      },
    ],
  },
  {
    description: "This is the description of the chapter",
    teacher_id: 1,
    name: "Chapter 1",
    id: "1",
    module_id: "1",

    chapter_number: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
    sections: [
      {
        name: "Section 1",
        course_id: "1",
        id: "1",
        videos: [
          {
            name: "Video 1",
            id: "1",
            url: "https://example.com/video1.mp4",
            section_id: "1",
            teacher_id: 1,
            createdAt: new Date(),
            groups: [1, 2, 3],
          },
          {
            name: "Video 2",
            id: "2",
            url: "https://example.com/video2.mp4",
            section_id: "1",
            teacher_id: 1,
            createdAt: new Date(),
            groups: [1, 2, 3],
          },
          {
            name: "Video 2",
            id: "2",
            url: "https://example.com/video2.mp4",
            section_id: "1",
            teacher_id: 1,
            createdAt: new Date(),
            groups: [1, 2, 3],
          },
        ],
        lectures: [
          {
            name: "Lecture 1",
            id: "3",
            content: "This is lecture content 1",
            section_id: "1",
            teacher_id: 1,
            createdAt: new Date(),
            groups: [1, 2, 3],
          },
          {
            name: "Lecture 1",
            id: "3",
            content: "This is lecture content 1",
            section_id: "1",
            teacher_id: 1,
            createdAt: new Date(),
            groups: [1, 2, 3],
          },
          {
            name: "Lecture 1",
            id: "3",
            content: "This is lecture content 1",
            section_id: "1",
            teacher_id: 1,
            createdAt: new Date(),
            groups: [1, 2, 3],
          },
        ],
        note: {
          name: "Note 1",
          id: "4",
          content: "This is note content 1",
          section_id: "1",
          teacher_id: 1,
          createdAt: new Date(),
          groups: [1, 2, 3],
        },
        files: [
          {
            name: "File 1",
            id: "5",
            section_id: "1",
            teacher_id: 1,
            createdAt: new Date(),
            groups: [1, 2, 3],
          },
          {
            name: "File 1",
            id: "5",
            section_id: "1",
            teacher_id: 1,
            createdAt: new Date(),
            groups: [1, 2, 3],
          },
          {
            name: "File 1",
            id: "5",
            section_id: "1",
            teacher_id: 1,
            createdAt: new Date(),
            groups: [1, 2, 3],
          },
          {
            name: "File 1",
            id: "5",
            section_id: "1",
            teacher_id: 1,
            createdAt: new Date(),
            groups: [1, 2, 3],
          },
        ],
      },
    ],
  },
  {
    description: "This is the description of the chapter",
    teacher_id: 1,

    name: "Chapter 1",
    id: "1",
    module_id: "1",
    chapter_number: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
    sections: [
      {
        name: "Section 1",
        course_id: "1",
        id: "1",
        videos: [
          {
            name: "Video 1",
            id: "1",
            url: "https://example.com/video1.mp4",
            section_id: "1",
            teacher_id: 1,
            createdAt: new Date(),
            groups: [1, 2, 3],
          },
          {
            name: "Video 2",
            id: "2",
            url: "https://example.com/video2.mp4",
            section_id: "1",
            teacher_id: 1,
            createdAt: new Date(),
            groups: [1, 2, 3],
          },
          {
            name: "Video 2",
            id: "2",
            url: "https://example.com/video2.mp4",
            section_id: "1",
            teacher_id: 1,
            createdAt: new Date(),

            groups: [1, 2, 3],
          },
        ],
        lectures: [
          {
            name: "Lecture 1",
            id: "3",
            content: "This is lecture content 1",
            section_id: "1",
            teacher_id: 1,
            createdAt: new Date(),
            groups: [1, 2, 3],
          },
          {
            name: "Lecture 1",
            id: "3",
            content: "This is lecture content 1",
            section_id: "1",
            teacher_id: 1,
            createdAt: new Date(),
            groups: [1, 2, 3],
          },
          {
            name: "Lecture 1",
            id: "3",
            content: "This is lecture content 1",
            section_id: "1",
            teacher_id: 1,
            createdAt: new Date(),
            groups: [1, 2, 3],
          },
        ],
        note: {
          name: "Note 1",
          id: "4",
          content: "This is note content 1",
          section_id: "1",
          teacher_id: 1,
          createdAt: new Date(),
          groups: [1, 2, 3],
        },
        files: [
          {
            name: "File 1",
            id: "5",
            section_id: "1",
            teacher_id: 1,
            createdAt: new Date(),
            groups: [1, 2, 3],
          },
          {
            name: "File 1",
            id: "5",
            section_id: "1",
            teacher_id: 1,
            createdAt: new Date(),
            groups: [1, 2, 3],
          },
          {
            name: "File 1",
            id: "5",
            section_id: "1",
            teacher_id: 1,
            createdAt: new Date(),
            groups: [1, 2, 3],
          },
          {
            name: "File 1",
            id: "5",
            section_id: "1",
            teacher_id: 1,
            createdAt: new Date(),
            groups: [1, 2, 3],
          },
        ],
      },
    ],
  },
];

export const moduleData: ModulesWithChapters = {
  name: "Module 1",
  id: "1",
  chapters: chaptersWithSections,
  teacher_id: 1,
  description: "This is the description of the module",
  coefficient: 1,
  image: "https://example.com/image.jpg",
  instructors: [1],
  isPublic: true,
  plan: ["Plan 1", "Plan 2", "Plan 3", "Plan 4"],
  semester: 1,
  speciality: "Speciality 1",
  year: 2021,
  createdAt: new Date(),
  updatedAt: new Date(),
};
