import {Module} from "@/types/chapter/courses";

export const dummyModules : Module[] = [{
    semester: 1,
    year: "2021",
    speciality: "Computer Science",
    coefficient: 3,
    teacher_id: "1",
    instructors: ["1", "2"],
    isPublic: true,
    plan: ["1", "2", "3"],
    image: "/store/img.jpg",
    name: "Module 1",
    id: "1",
    createdAt: new Date(),
    updatedAt: new Date(),
    courses:[]
},
    {
        semester: 1,
        year: "2021",
        speciality: "Computer Science",
        coefficient: 3,
        teacher_id: "1",
        instructors: ["1", "2"],
        isPublic: true,
        plan: ["1", "2", "3"],
        image: "/store/img.jpg",
        name: "Module 1",
        id: "1",
        createdAt: new Date(),
        updatedAt: new Date(),
        courses:[]
    },
    {
        semester: 1,
        year: "2021",
        speciality: "Computer Science",
        coefficient: 3,
        teacher_id: "1",
        instructors: ["1", "2"],
        isPublic: true,
        plan: ["1", "2", "3"],
        image: "/store/img.jpg",
        name: "Module 1",
        id: "1",
        createdAt: new Date(),
        updatedAt: new Date(),
        courses:[]
    },
    {
        semester: 1,
        year: "2021",
        speciality: "Computer Science",
        coefficient: 3,
        teacher_id: "1",
        instructors: ["1", "2"],
        isPublic: true,
        plan: ["1", "2", "3"],
        image: "/store/img.jpg",
        name: "Module 1",
        id: "1",
        createdAt: new Date(),
        updatedAt: new Date(),
        courses:[]
    },
    {
        semester: 1,
        year: "2021",
        speciality: "Computer Science",
        coefficient: 3,
        teacher_id: "1",
        instructors: ["1", "2"],
        isPublic: true,
        plan: ["1", "2", "3"],
        image: "/store/img.jpg",
        name: "Module 1",
        id: "1",
        createdAt: new Date(),
        updatedAt: new Date(),
        courses:[]
    },
    {
        semester: 1,
        year: "2021",
        speciality: "Computer Science",
        coefficient: 3,
        teacher_id: "1",
        instructors: ["1", "2"],
        isPublic: true,
        plan: ["1", "2", "3"],
        image: "/store/img.jpg",
        name: "Module 1",
        id: "1",
        createdAt: new Date(),
        updatedAt: new Date(),
        courses:[]
    },
    {
        semester: 1,
        year: "2021",
        speciality: "Computer Science",
        coefficient: 3,
        teacher_id: "1",
        instructors: ["1", "2"],
        isPublic: true,
        plan: ["1", "2", "3"],
        image: "/store/img.jpg",
        name: "Module 1",
        id: "1",
        createdAt: new Date(),
        updatedAt: new Date(),
        courses:[]
    }]