import type { Metadata } from "next";
import "./prosemirror.css";
import { Almarai } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
const monts = Almarai({
  weight: ["400","300","700","800"],
  subsets: ["arabic"],
  style: ["normal"],
  display: "swap",
});
export const metadata: Metadata = {
  title: "Madaurus",
  description: "Generated by create next app",
  icons: ["/assets/icons/logo.jpg"],
};
import "./globals.css";
import { cn } from "@/lib/utils";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" title="Madaurus" className={monts.className}>
      <body className="w-full h-full">
        {children}
        <Toaster />
      </body>
    </html>
  );
}
