import type { Metadata } from 'next';
import './globals.css';
import { Montserrat } from 'next/font/google';
import { Toaster } from '@/components/ui/sonner';
const monts = Montserrat({
	weight: ['300', '400', '500', '600', '700'],
	subsets: ['latin'],
	style: ['normal'],
	variable: '--font-montserrat',
	display: 'swap',
});
export const metadata: Metadata = {
	title: 'Madaurus',
	description: 'Generated by create next app',
	icons: ['/assets/icons/logo.jpg'],
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={monts.className}>
				{children}
				<Toaster />
			</body>
		</html>
	);
}
