export const quizzes = [
  {
    id: "60c72b2f4f1a2c001f9e67b2",
    module_id: "60c72b2f4f1a2c001f9e67b3",
    teacher_id: "teacher123",
    title: "Introduction to Biology",
    instructions: "Answer all the questions within the time limit.",
    image: "https://example.com/quiz_image.jpg",
    question_count: 10,
    max_score: 100,
    min_score: 50,
    start_date: "2023-05-01T08:00:00Z",
    end_date: "2023-05-31T23:59:59Z",
    duration: 60,
    questions: [
      {
        id: 1,
        body: "What is the powerhouse of the cell?",
        score: 10,
        image: "",
        options: [
          { id: 1, option: "Nucleus" },
          { id: 2, option: "Mitochondria" },
          { id: 3, option: "Ribosome" },
          { id: 4, option: "Endoplasmic Reticulum" },
        ],
        correct_idxs: [1],
      },
      {
        id: 2,
        body: "Which of the following is a prokaryotic organism?",
        score: 15,
        image: "https://example.com/question_image.jpg",
        options: [
          { id: 1, option: "Bacteria" },
          { id: 2, option: "Fungi" },
          { id: 3, option: "Plants" },
          { id: 4, option: "Animals" },
        ],
        correct_idxs: ["0"],
      },
    ],
    grades: [
      { min: 90, max: 100, grade: "A" },
      { min: 80, max: 89, grade: "B" },
      { min: 70, max: 79, grade: "C" },
      { min: 60, max: 69, grade: "D" },
      { min: 0, max: 59, grade: "F" },
    ],
  },
  {
    id: "60c72b2f4f1a2c001f9e67b4",
    module_id: "60c72b2f4f1a2c001f9e67b5",
    teacher_id: "teacher456",
    title: "Advanced Mathematics",
    instructions: "Solve the following problems within the given time.",
    image: "https://example.com/quiz_image_math.jpg",
    question_count: 5,
    max_score: 50,
    min_score: 25,
    start_date: "2023-06-01T08:00:00Z",
    end_date: "2023-06-30T23:59:59Z",
    duration: 45,
    questions: [
      {
        id: 1,
        body: "What is the integral of x^2?",
        score: 10.0,
        image: "",
        options: [
          { id: 1, option: "x^3/3 + C" },
          { id: 2, option: "2x + C" },
          { id: 3, option: "x^2/2 + C" },
          { id: 4, option: "x^3/2 + C" },
        ],
        correct_idxs: ["0"],
      },
      {
        id: 2,
        body: "Solve the equation: 2x + 3 = 7",
        score: 15,
        image: "https://example.com/question_image_math.jpg",
        options: [
          { id: 1, option: "x = 1" },
          { id: 2, option: "x = 2" },
          { id: 3, option: "x = 3" },
          { id: 4, option: "x = 4" },
        ],
        correct_idxs: ["1"],
      },
    ],
    grades: [
      { min: 45, max: 50, grade: "A" },
      { min: 40, max: 44, grade: "B" },
      { min: 35, max: 39, grade: "C" },
      { min: 30, max: 34, grade: "D" },
      { min: 0, max: 29, grade: "F" },
    ],
  },
];

export const quiz = {
  id: "60c72b2f4f1a2c001f9e67b2",
  module_id: "66453ff8a9a6b2a1a507b8a2",
  teacher_id: "teacher123",
  title: "Introduction to Biology",
  instructions: "Answer all the questions within the time limit.",
  image:
    "https://firebasestorage.googleapis.com/v0/b/madaurus-71e46.appspot.com/o/2023-10-16-230326.jpg?alt=media&token=d1bb5325-296d-477a-b3cb-dc9f57d0f691",
  question_count: 10,
  max_score: 100,
  min_score: 50,
  start_date: "2023-05-01T08:00:00",
  end_date: "2023-05-31T23:59:59",
  duration: 60,
  questions: [
    {
      id: "1",
      body: "What is the powerhouse of the cell?",
      score: 10,
      image:
        "https://firebasestorage.googleapis.com/v0/b/madaurus-71e46.appspot.com/o/2023-10-16-230326.jpg?alt=media&token=d1bb5325-296d-477a-b3cb-dc9f57d0f691",
      options: [
        { id: "1", option: "Nucleus" },
        { id: "2", option: "Mitochondria" },
        { id: "3", option: "Ribosome" },
        { id: "4", option: "Endoplasmic Reticulum" },
      ],
      correct_idxs: ["1"],
    },
    {
      id: "2",
      body: "Which of the following is a prokaryotic organism?",
      score: 10,
      image:
        "https://firebasestorage.googleapis.com/v0/b/madaurus-71e46.appspot.com/o/2023-10-16-230326.jpg?alt=media&token=d1bb5325-296d-477a-b3cb-dc9f57d0f691",
      options: [
        { id: "1", option: "Bacteria" },
        { id: "2", option: "Fungi" },
        { id: "3", option: "Plants" },
        { id: "4", option: "Animals" },
      ],
      correct_idxs: ["1"],
    },
    {
      id: "3",
      body: "Hala Madrid ?",
      score: 15,
      image:
        "https://firebasestorage.googleapis.com/v0/b/madaurus-71e46.appspot.com/o/2023-10-16-230326.jpg?alt=media&token=d1bb5325-296d-477a-b3cb-dc9f57d0f691",
      options: [
        { id: "1", option: "Bacteria" },
        { id: "2", option: "Fungi" },
        { id: "3", option: "Plants" },
        { id: "4", option: "Animals" },
      ],
      correct_idxs: ["1"],
    },
  ],
  grades: [
    { min: 90, max: 100, grade: "A" },
    { min: 80, max: 89, grade: "B" },
    { min: 70, max: 79, grade: "C" },
    { min: 60, max: 69, grade: "D" },
    { min: 0, max: 59, grade: "F" },
  ],
};
