import { IQuiz, QuizState } from "@/types/quiz";

export const quiz: any= [
  {
    id: "1",
    title: "Mathematics",
    description: "This is a mathematics quiz",
    duration: 60,
    category: "Devoir",
    image: "/images/quiz/quiz1.jpg",
    startDate: "2021-09-01",
    endDate: "2021-09-01",
    questions: 10,
    publisher: "Admin",
    state: QuizState.FINISHED,
    module_name: "Mathematics",
    points: 10,
    attempts: 3,
  },
  {
    id: "2",
    title: "Physics",
    description: "This is a physics quiz",
    duration: 60,
    category: "Quiz",
    image: "/images/quiz/quiz2.jpg",
    startDate: "2021-09-01",
    endDate: "2021-09-01",
    questions: 10,
    publisher: "Admin",
    state: QuizState.UPCOMING,
    module_name: "Physics",
    points: 10,
    attempts: 3,
  },
  {
    id: "3",
    title: "Chemistry",
    description: "This is a chemistry quiz",
    duration: 60,
    category: "Test",
    image: "/images/quiz/quiz3.jpg",
    startDate: "2021-09-01",
    endDate: "2021-09-01",
    questions: 10,
    publisher: "Admin",
    state: QuizState.FINISHED,
    module_name: "Chemistry",
    points: 10,
    attempts: 3,
  },
  {
    id: "1",
    title: "Mathematics",
    description: "This is a mathematics quiz",
    duration: 60,
    category: "Devoir",
    image: "/images/quiz/quiz1.jpg",
    startDate: "2021-09-01",
    endDate: "2021-09-01",
    questions: 10,
    publisher: "Admin",
    state: QuizState.ONGOING,
    module_name: "Mathematics",
    points: 10,
    attempts: 3,
  },
  {
    id: "2",
    title: "Physics",
    description: "This is a physics quiz",
    duration: 60,
    category: "Quiz",
    image: "/images/quiz/quiz2.jpg",
    startDate: "2021-09-01",
    endDate: "2021-09-01",
    questions: 10,
    publisher: "Admin",
    state: QuizState.ONGOING,
    module_name: "Physics",
    points: 10,
    attempts: 3,
  },
  {
    id: "3",
    title: "Chemistry",
    description: "This is a chemistry quiz",
    duration: 60,
    category: "Test",
    image: "/images/quiz/quiz3.jpg",
    startDate: "2021-09-01",
    endDate: "2021-09-01",
    questions: 10,
    publisher: "Admin",
    state: QuizState.UPCOMING,
    module_name: "Chemistry",
    points: 10,
    attempts: 3,
  },
  {
    id: "1",
    title: "Mathematics",
    description: "This is a mathematics quiz",
    duration: 60,
    category: "Devoir",
    image: "/images/quiz/quiz1.jpg",
    startDate: "2021-09-01",
    endDate: "2021-09-01",
    questions: 10,
    publisher: "Admin",
    state: QuizState.FINISHED,
    module_name: "Mathematics",
    points: 10,
    attempts: 3,
  },
  {
    id: "2",
    title: "Physics",
    description: "This is a physics quiz",
    duration: 60,
    category: "Quiz",
    image: "/images/quiz/quiz2.jpg",
    startDate: "2021-09-01",
    endDate: "2021-09-01",
    questions: 10,
    publisher: "Admin",
    state: QuizState.ONGOING,
    module_name: "Physics",
    points: 10,
    attempts: 3,
  },
  {
    id: "3",
    title: "Chemistry",
    description: "This is a chemistry quiz",
    duration: 60,
    category: "Test",
    image: "/images/quiz/quiz3.jpg",
    startDate: "2021-09-01",
    endDate: "2021-09-01",
    questions: 10,
    publisher: "Admin",
    state: QuizState.FINISHED,
    module_name: "Chemistry",
    points: 10,
    attempts: 3,
  },
  {
    id: "1",
    title: "Mathematics",
    description: "This is a mathematics quiz",
    duration: 60,
    category: "Devoir",
    image: "/images/quiz/quiz1.jpg",
    startDate: "2021-09-01",
    endDate: "2021-09-01",
    questions: 10,
    publisher: "Admin",
    state: QuizState.UPCOMING,
    module_name: "Mathematics",
    points: 10,
    attempts: 3,
  },
  {
    id: "2",
    title: "Physics",
    description: "This is a physics quiz",
    duration: 60,
    category: "Quiz",
    image: "/images/quiz/quiz2.jpg",
    startDate: "2021-09-01",
    endDate: "2021-09-01",
    questions: 10,
    publisher: "Admin",
    state: QuizState.ONGOING,
    module_name: "Physics",
    points: 10,
    attempts: 3,
  },
  {
    id: "3",
    title: "Chemistry",
    description: "This is a chemistry quiz",
    duration: 60,
    category: "Test",
    image: "/images/quiz/quiz3.jpg",
    startDate: "2021-09-01",
    endDate: "2021-09-01",
    questions: 10,
    publisher: "Admin",
    state: QuizState.FINISHED,
    module_name: "Chemistry",
    points: 10,
    attempts: 3,
  },
];
