import {IQuiz, QuizState} from "@/types/quiz";

export const quiz: IQuiz[] = [
  {
    id: "1",
    title: "Mathematics",
    description: "This is a mathematics quiz",
    duration: 60,
    category: "Devoir",
    image: "/images/quiz/quiz1.jpg",
    start: "2021-09-01",
    end: "2021-09-01",
    questions: 10,
    publisher: "Admin",
    state:  QuizState.FINISHED,
    module_name: "Mathematics",
  },
  {
    id: "2",
    title: "Physics",
    description: "This is a physics quiz",
    duration: 60,
    category: "Quiz",
    image: "/images/quiz/quiz2.jpg",
    start: "2021-09-01",
    end: "2021-09-01",
    questions: 10,
    publisher: "Admin",
    state:  QuizState.UPCOMING,
    module_name: "Physics",
  },
  {
    id: "3",
    title: "Chemistry",
    description: "This is a chemistry quiz",
    duration: 60,
    category: "Test",
    image: "/images/quiz/quiz3.jpg",
    start: "2021-09-01",
    end: "2021-09-01",
    questions: 10,
    publisher: "Admin",
    state: QuizState.FINISHED,
    module_name: "Chemistry",
  },
  {
    id: "1",
    title: "Mathematics",
    description: "This is a mathematics quiz",
    duration: 60,
    category: "Devoir",
    image: "/images/quiz/quiz1.jpg",
    start: "2021-09-01",
    end: "2021-09-01",
    questions: 10,
    publisher: "Admin",
    state: QuizState.ONGOING,
    module_name: "Mathematics",
  },
  {
    id: "2",
    title: "Physics",
    description: "This is a physics quiz",
    duration: 60,
    category: "Quiz",
    image: "/images/quiz/quiz2.jpg",
    start: "2021-09-01",
    end: "2021-09-01",
    questions: 10,
    publisher: "Admin",
    state: QuizState.ONGOING,
    module_name: "Physics",
  },
  {
    id: "3",
    title: "Chemistry",
    description: "This is a chemistry quiz",
    duration: 60,
    category: "Test",
    image: "/images/quiz/quiz3.jpg",
    start: "2021-09-01",
    end: "2021-09-01",
    questions: 10,
    publisher: "Admin",
    state: QuizState.UPCOMING,
    module_name: "Chemistry",
  },
  {
    id: "1",
    title: "Mathematics",
    description: "This is a mathematics quiz",
    duration: 60,
    category: "Devoir",
    image: "/images/quiz/quiz1.jpg",
    start: "2021-09-01",
    end: "2021-09-01",
    questions: 10,
    publisher: "Admin",
    state: QuizState.FINISHED,
    module_name: "Mathematics",
  },
  {
    id: "2",
    title: "Physics",
    description: "This is a physics quiz",
    duration: 60,
    category: "Quiz",
    image: "/images/quiz/quiz2.jpg",
    start: "2021-09-01",
    end: "2021-09-01",
    questions: 10,
    publisher: "Admin",
    state: QuizState.ONGOING,
    module_name: "Physics",
  },
  {
    id: "3",
    title: "Chemistry",
    description: "This is a chemistry quiz",
    duration: 60,
    category: "Test",
    image: "/images/quiz/quiz3.jpg",
    start: "2021-09-01",
    end: "2021-09-01",
    questions: 10,
    publisher: "Admin",
    state: QuizState.FINISHED,
    module_name: "Chemistry",
  },
  {
    id: "1",
    title: "Mathematics",
    description: "This is a mathematics quiz",
    duration: 60,
    category: "Devoir",
    image: "/images/quiz/quiz1.jpg",
    start: "2021-09-01",
    end: "2021-09-01",
    questions: 10,
    publisher: "Admin",
    state: QuizState.UPCOMING,
    module_name: "Mathematics",
  },
  {
    id: "2",
    title: "Physics",
    description: "This is a physics quiz",
    duration: 60,
    category: "Quiz",
    image: "/images/quiz/quiz2.jpg",
    start: "2021-09-01",
    end: "2021-09-01",
    questions: 10,
    publisher: "Admin",
    state: QuizState.ONGOING,
    module_name: "Physics",
  },
  {
    id: "3",
    title: "Chemistry",
    description: "This is a chemistry quiz",
    duration: 60,
    category: "Test",
    image: "/images/quiz/quiz3.jpg",
    start: "2021-09-01",
    end: "2021-09-01",
    questions: 10,
    publisher: "Admin",
    state: QuizState.FINISHED,
    module_name: "Chemistry",
  },
];
